"""Update the og:image meta tag in every HTML page to point to the
page-specific OG card in src/images/og/ generated by generate-og-images.py.

Falls back to og-default.jpg for any page that doesn't have a bespoke card.
Also sets twitter:image to the same URL.
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).parent / "src"
SITE_URL = "https://functional-patterns-brisbane.vercel.app"

# Map HTML file (relative to src/) -> og image filename (relative to images/og/)
PAGE_TO_OG: dict[str, str] = {
    "index.html": "og-home.jpg",
    "book.html": "og-book.jpg",
    "contact.html": "og-contact.jpg",
    "results.html": "og-results.jpg",
    "team.html": "og-team.jpg",
    "what-we-treat.html": "og-what-we-treat.jpg",
    "how-we-work.html": "og-how-we-work.jpg",
    "programs.html": "og-programs.jpg",
    "online.html": "og-online.jpg",
    "privacy.html": "og-default.jpg",
    "conditions/chronic-pain.html": "og-chronic-pain.jpg",
    "conditions/scoliosis.html": "og-scoliosis.jpg",
    "conditions/posture-correction.html": "og-posture.jpg",
    # Remaining conditions / programs / research use the default card.
}

OG_IMAGE_RE = re.compile(
    r'(<meta property="og:image" content=")[^"]+(")',
)
TWITTER_IMAGE_RE = re.compile(
    r'(<meta name="twitter:image" content=")[^"]+(")',
)


def og_url_for(rel_path: str) -> str:
    og_filename = PAGE_TO_OG.get(rel_path, "og-default.jpg")
    return f"{SITE_URL}/images/og/{og_filename}"


def has_twitter_image(content: str) -> bool:
    return "twitter:image" in content


def ensure_twitter_image(content: str, og_url: str) -> str:
    """Add twitter:image tag alongside twitter:card if missing."""
    if has_twitter_image(content):
        return TWITTER_IMAGE_RE.sub(rf'\1{og_url}\2', content)

    # Insert a twitter:image tag right after the twitter:card tag.
    marker_re = re.compile(r'(<meta name="twitter:card"[^>]*>)')
    twitter_tag = f'\n  <meta name="twitter:image" content="{og_url}">'
    if marker_re.search(content):
        return marker_re.sub(rf'\1{twitter_tag}', content, count=1)
    return content


def process(path: Path) -> bool:
    rel = str(path.relative_to(ROOT)).replace("\\", "/")
    content = path.read_text(encoding="utf-8")
    original = content

    og_url = og_url_for(rel)
    content = OG_IMAGE_RE.sub(rf'\1{og_url}\2', content)
    content = ensure_twitter_image(content, og_url)

    if content != original:
        path.write_text(content, encoding="utf-8")
        return True
    return False


def main() -> None:
    html_files = sorted(ROOT.rglob("*.html"))
    changed = 0
    for path in html_files:
        if process(path):
            changed += 1
            rel = path.relative_to(ROOT)
            target = PAGE_TO_OG.get(str(rel).replace("\\", "/"), "og-default.jpg")
            print(f"  {rel}  ->  {target}")
    print()
    print(f"Updated: {changed}/{len(html_files)} files")


if __name__ == "__main__":
    main()
